apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: orders:v2
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
