apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
  - name: busybox-container
    image: busybox:latest
    command: ["sleep", "3600"]
# kubeclt apply -f one-pod-two-container.yaml
# “In Kubernetes, multiple containers in a pod share the same network namespace, so they can communicate via localhost.”
# his container will do nothing but stay alive for 3600 seconds (1 hour).
